import { cellLookup, freeMask, generateCard, playableMask, type BingoCard } from '../bingo/cards.ts';
import { isComplete, PATTERNS_75, winningCells, type Pattern75Id } from '../bingo/patterns.ts';
import { range, sample, type Rng } from '../rng/fair.ts';

/**
 * BEACH ADVENTURE — free-to-play level map (the casual, non-wagering mode).
 *
 * Each level: 1–4 cards, a target pattern and a ball budget. Balls are called on a timer;
 * the player daubs called numbers and must shout BINGO before the balls run out.
 * Stars reward a fast bingo; coins buy boosters. Win rates per level (for a perfect dauber)
 * are verified by simulation in the test-suite so the difficulty curve stays sane.
 */
export interface Zone {
  id: number;
  name: string;
}

export const ZONES: readonly Zone[] = [
  { id: 1, name: 'Palm Cove' },
  { id: 2, name: 'Coral Reef' },
  { id: 3, name: 'Shipwreck Bay' },
  { id: 4, name: 'Volcano Isle' },
];

export const LEVELS_PER_ZONE = 10;

export interface LevelDef {
  id: number;
  zone: number;
  cards: number;
  pattern: Pattern75Id;
  maxBalls: number;
  /** Claim BINGO by this ball for 3★ (by `stars[1]` for 2★). */
  stars: readonly [number, number];
  callMs: number;
  /** Coins for a 1-star win; ×2 for 2 stars, ×3 for 3 stars. */
  reward: number;
}

type Row = [cards: number, pattern: Pattern75Id, maxBalls: number, threeStarBall: number, twoStarBall: number];

// Generated by simulation (see scripts/tune-levels.ts): the ball budget gives a perfect dauber
// a ≈95% win rate on level 1 sliding to ≈65% by level 39 (60% for the blackout finale);
// star thresholds are the 30th / 65th percentile of the ball on which the pattern first completes.
const TABLE: Row[] = [
  // Palm Cove
  [1, 'line', 57, 36, 46],
  [1, 'postageStamp', 63, 41, 52],
  [2, 'line', 48, 31, 39],
  [1, 'fourCorners', 74, 56, 68],
  [2, 'postageStamp', 55, 36, 45],
  [2, 'twoLines', 54, 42, 48],
  [3, 'line', 43, 29, 36],
  [2, 'fourCorners', 69, 49, 61],
  [3, 'postageStamp', 49, 33, 42],
  [2, 'x', 72, 61, 68],
  // Coral Reef
  [3, 'twoLines', 50, 40, 46],
  [3, 'fourCorners', 64, 45, 57],
  [3, 'diamond', 69, 58, 65],
  [4, 'line', 39, 27, 34],
  [3, 'letterT', 69, 59, 66],
  [4, 'postageStamp', 44, 30, 39],
  [3, 'plus', 69, 59, 66],
  [4, 'twoLines', 47, 38, 44],
  [3, 'letterL', 70, 60, 67],
  [4, 'x', 66, 57, 64],
  // Shipwreck Bay
  [4, 'fourCorners', 59, 42, 54],
  [4, 'diamond', 66, 57, 64],
  [4, 'letterT', 66, 57, 64],
  [4, 'plus', 66, 57, 64],
  [4, 'letterL', 67, 59, 65],
  [4, 'twoLines', 46, 38, 44],
  [4, 'frame', 71, 66, 70],
  [4, 'postageStamp', 41, 30, 39],
  [4, 'x', 65, 57, 64],
  [4, 'diamond', 65, 57, 64],
  // Volcano Isle
  [4, 'line', 35, 27, 34],
  [4, 'twoLines', 45, 38, 44],
  [4, 'fourCorners', 55, 42, 54],
  [4, 'x', 64, 57, 64],
  [4, 'plus', 65, 57, 64],
  [4, 'frame', 70, 66, 70],
  [4, 'letterT', 64, 57, 64],
  [4, 'diamond', 64, 57, 64],
  [4, 'frame', 70, 66, 70],
  [4, 'blackout', 71, 69, 72],
];

export const LEVELS: readonly LevelDef[] = TABLE.map(([cards, pattern, maxBalls, three, two], i) => ({
  id: i + 1,
  zone: Math.floor(i / LEVELS_PER_ZONE) + 1,
  cards,
  pattern,
  maxBalls,
  stars: [three, two] as const,
  callMs: Math.round(2600 - (i * 1000) / 39),
  reward: 20 + i * 5,
}));

export type BoosterId = 'seagull' | 'crab' | 'wave' | 'sun';

export const BOOSTERS: Readonly<Record<BoosterId, { name: string; description: string; price: number }>> = {
  seagull: { name: 'Seagull Auto-Daub', description: 'Daubs every called number for you this level.', price: 120 },
  crab: { name: 'Crab Pinch', description: 'Daub any one square, called or not.', price: 80 },
  wave: { name: 'Big Wave', description: '+5 balls when you run out.', price: 100 },
  sun: { name: 'Golden Sun', description: 'Double coins for this level.', price: 60 },
};

export type LevelStatus = 'playing' | 'won' | 'lost';

export interface LevelRun {
  level: LevelDef;
  cards: BingoCard[];
  lookups: Int8Array[];
  playable: number[];
  /** Player daubs per card (free spaces pre-daubed). */
  daubs: number[];
  drum: number[];
  drawnCount: number;
  extraBalls: number;
  autoDaub: boolean;
  doubleCoins: boolean;
  status: LevelStatus;
  score: number;
  /** Balls remaining when BINGO was claimed. */
  ballsLeftAtBingo: number;
  /** Balls called when BINGO was claimed. */
  ballAtBingo: number;
  winningCard: number;
  falseClaims: number;
}

export function startLevel(level: LevelDef, rng: Rng, opts: { autoDaub?: boolean; doubleCoins?: boolean } = {}): LevelRun {
  const cards = range(1, level.cards).map(() => generateCard('75', rng));
  return {
    level,
    cards,
    lookups: cards.map(cellLookup),
    playable: cards.map(playableMask),
    daubs: cards.map(freeMask),
    drum: sample(range(1, 75), 75, rng),
    drawnCount: 0,
    extraBalls: 0,
    autoDaub: Boolean(opts.autoDaub),
    doubleCoins: Boolean(opts.doubleCoins),
    status: 'playing',
    score: 0,
    ballsLeftAtBingo: 0,
    ballAtBingo: 0,
    winningCard: -1,
    falseClaims: 0,
  };
}

export function ballBudget(run: LevelRun): number {
  return Math.min(75, run.level.maxBalls + run.extraBalls);
}

export function ballsLeft(run: LevelRun): number {
  return ballBudget(run) - run.drawnCount;
}

export function calledBalls(run: LevelRun): number[] {
  return run.drum.slice(0, run.drawnCount);
}

export const DAUB_POINTS = 50;
export const SPEED_POINTS = 50;
export const BINGO_POINTS = 1000;
export const BALL_LEFT_POINTS = 100;

/** Call the next ball (or null when the budget is spent). */
export function callBall(run: LevelRun): number | null {
  if (run.status !== 'playing' || ballsLeft(run) <= 0) return null;
  const ball = run.drum[run.drawnCount++]!;
  if (run.autoDaub) {
    run.lookups.forEach((lookup, i) => {
      const cell = lookup[ball] ?? -1;
      if (cell >= 0 && !(run.daubs[i]! & (1 << cell))) {
        run.daubs[i]! |= 1 << cell;
        run.score += DAUB_POINTS;
      }
    });
  }
  return ball;
}

/** Player taps a square. Only called numbers can be daubed; returns whether it counted. */
export function daub(run: LevelRun, cardIndex: number, cell: number, reactionMs?: number): boolean {
  if (run.status !== 'playing') return false;
  const card = run.cards[cardIndex];
  if (!card || cell < 0 || cell >= card.cells.length) return false;
  if (run.daubs[cardIndex]! & (1 << cell)) return false;
  const value = card.cells[cell]!;
  if (value <= 0 || !run.drum.slice(0, run.drawnCount).includes(value)) return false;
  run.daubs[cardIndex]! |= 1 << cell;
  const speed = reactionMs === undefined ? 0 : Math.max(0, 1 - reactionMs / run.level.callMs);
  run.score += DAUB_POINTS + Math.round(SPEED_POINTS * speed);
  return true;
}

/** Crab Pinch booster: daub any square. */
export function crabPinch(run: LevelRun, cardIndex: number, cell: number): boolean {
  if (run.status !== 'playing') return false;
  const card = run.cards[cardIndex];
  if (!card || card.cells[cell] === undefined || card.cells[cell]! <= 0) return false;
  if (run.daubs[cardIndex]! & (1 << cell)) return false;
  run.daubs[cardIndex]! |= 1 << cell;
  return true;
}

export function addBalls(run: LevelRun, count: number): void {
  run.extraBalls += count;
  if (run.status === 'lost') run.status = 'playing';
}

/** Cards whose *daubed* squares complete the level pattern. */
export function bingoCards(run: LevelRun): number[] {
  const pattern = PATTERNS_75[run.level.pattern];
  return run.daubs.flatMap((d, i) => (isComplete(d, pattern, run.playable[i]!) ? [i] : []));
}

export function winningShape(run: LevelRun, cardIndex: number): number[] {
  return winningCells(run.daubs[cardIndex]!, PATTERNS_75[run.level.pattern], run.playable[cardIndex]!);
}

export function claimBingo(run: LevelRun): boolean {
  if (run.status !== 'playing') return false;
  const winners = bingoCards(run);
  if (!winners.length) {
    run.falseClaims++;
    run.score = Math.max(0, run.score - 200);
    return false;
  }
  run.status = 'won';
  run.winningCard = winners[0]!;
  run.ballsLeftAtBingo = ballsLeft(run);
  run.ballAtBingo = run.drawnCount;
  run.score += BINGO_POINTS + run.ballsLeftAtBingo * BALL_LEFT_POINTS;
  return true;
}

/** Mark the run lost once the budget is spent (the UI gives a short grace period first). */
export function outOfBalls(run: LevelRun): boolean {
  if (run.status === 'playing' && ballsLeft(run) <= 0) run.status = 'lost';
  return run.status === 'lost';
}

/** 3★ / 2★ for a bingo claimed by the level's star thresholds, else 1★. */
export function starsFor(run: LevelRun): 0 | 1 | 2 | 3 {
  if (run.status !== 'won') return 0;
  const [three, two] = run.level.stars;
  return run.ballAtBingo <= three ? 3 : run.ballAtBingo <= two ? 2 : 1;
}

export function coinsFor(run: LevelRun): number {
  return run.level.reward * starsFor(run) * (run.doubleCoins ? 2 : 1);
}

/** Probability a perfect player (auto-daub, instant claim) beats the level — Monte Carlo. */
export function levelWinRate(level: LevelDef, rng: Rng, trials: number): number {
  let wins = 0;
  for (let t = 0; t < trials; t++) {
    const run = startLevel(level, rng, { autoDaub: true });
    while (run.status === 'playing' && callBall(run) !== null) {
      if (bingoCards(run).length) claimBingo(run);
    }
    if (run.status === 'won') wins++;
  }
  return wins / trials;
}
